### ISSUE TITLE
Use VK_API_VERSION_1_2 instead of VK_VERSION_1_2

### ISSUE THREAD

**Issue by mdietrich16** [Pilzschaf/VulkanTutorial#1]
I am on Arch Linux and I just spent the last 4 hours trying to find the source of a segfault and a VK_ERROR_INCOMPATIBLE_DRIVER. The source was line 7 in vulkan_device.cpp in v003 of the file. You use VK_VERSION_1_2 to specify the version of Vulkan to be used, but I believe using this is deprecated and leads to the mentioned errors. If I replace it with VK_API_VERSION_1_2 it works and is the supported way to do it, I think. I know this could have been done as a PR but I'm to lazy right now.

Gute Serie btw :)

**Comment by mdietrich16** [comment]
Ok, nevermind. Apparantly, I'm just dumb and did not look at the later versions of your code, where you have exactly this change done. Sorry to bother.

**Comment by Pilzschaf** [comment]
I have now added a small comment for both affected versions v003 and v004 to prevent confusion for other people.
